Update webhook_remover.py
letsbuilda/anubis pull request #79
Opened 2023-06-03 18:46 UTC by IlluminatiFish

Fix an annoying problem

2023-06-03 19:38 UTC, Robin5605 approved these changes

2023-06-03 19:38 UTC, Robin5605 commented on src/bot/exts/filters/webhook_remover.py
> +        if len(message.content) != len(webhook_url):
Could also check `if message.content == webhook_url`

2023-06-04 08:17 UTC, shenanigansd requested changes
Please restrict this exemption to users with the `@Security` role and messages in the `#soc` category.

2023-06-04 20:50 UTC, Robin5605 submitted a review, later dismissed

2023-06-04 21:13 UTC, shenanigansd submitted a review, later dismissed

2023-06-04 21:19 UTC, shenanigansd approved these changes

2023-06-04 21:19 UTC, merged